# This is a nightly workflow based on https://gitlab.kitware.com/cmake/cmake/-/blob/master/Help/dev/testing.rst

name: Nightly-CI

# Controls when the workflow will run
on:
  # Periodic build
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC 
  - cron:  '0 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: '[matlab:${{ matrix.matlab_version }}:${{ matrix.os }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        os: [ubuntu-20.04, macos-10.15]
        matlab_version: [R2020a, R2020b, R2021a, latest]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Linux-specific dependencies
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install cmake build-essential libssl-dev

      - name: Install dependencies
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}/Dashboards/Scripts
          curl -O https://gitlab.kitware.com/cmake/dashboard-scripts/-/raw/master/cmake_common.cmake 

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.matlab_version }}

      - name: Run Nightly Test
        shell: bash
        run: |
          env
          which matlab
          ctest --version
          ctest -S ${GITHUB_WORKSPACE}/Dashboards/Scripts/matlab_dashboard.cmake -V
