# This is a nightly workflow based on https://gitlab.kitware.com/cmake/cmake/-/blob/master/Help/dev/testing.rst

name: Nightly-CI

# Controls when the workflow will run
on:
  # Periodic build
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC 
  - cron:  '0 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install cmake build-essential libssl-dev
          cd ${GITHUB_WORKSPACE}/Dashboards/Scripts
          wget https://gitlab.kitware.com/cmake/dashboard-scripts/-/raw/master/cmake_common.cmake 

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Run Nightly Test
        run: |
          env
          which matlab
          ctest --version
          # For this test, manually run CMake's tests
          git clone https://gitlab.kitware.com/traversaro/cmake.git -b fix/22646
          cd cmake
          mkdir build
          cd build
          cmake -DBUILD_TESTING:BOOL=ON -DCMake_TEST_FindMatlab:BOOL=TRUE ..
          make -j10
          ctest -VV -R Matlab
          # ctest -S ${GITHUB_WORKSPACE}/Dashboards/Scripts/matlab_dashboard.cmake -V
